# Generated by Django 5.1.15 on 2026-01-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
