# Generated by Django 5.1.15 on 2026-01-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_clientprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
