# Generated by Django 5.1.15 on 2026-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='operations', to='profile.driverprofile'),
        ),
    ]
