# Generated by Django 5.1.15 on 2026-01-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation_drivers'),
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='drivers',
        ),
        migrations.AddField(
            model_name='operation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='profile.driverprofile'),
        ),
    ]
